# Generated by Django 5.1.5 on 2025-02-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_bought',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
