# Generated by Django 5.1.5 on 2025-02-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_courses_course_bought'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('email_id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('course_object', models.CharField(max_length=100)),
            ],
        ),
    ]
