# Generated by Django 5.1.5 on 2025-02-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='course_object',
            new_name='course_IDS',
        ),
    ]
