# Generated by Django 5.1.5 on 2025-02-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_course_object_cart_course_ids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
