# Generated by Django 5.1.5 on 2025-02-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_use', models.EmailField(max_length=254)),
                ('course_IDS', models.CharField(max_length=100)),
            ],
        ),
    ]
